app:
  # speech model
  is_pretrained: False

  pretrained_section: # (nemo, hf)
    model_name: ${}
    use_nemo: False
  # 
  model_path: ??
  
  processor:
    sample_rate: 16000

	# vocab
  vocab: []

	# logger
  log:
    dir: ??
	file: ??